Update build_loop.yml

diff --git a/.github/workflows/build_loop.yml b/.github/workflows/build_loop.yml
--- a/.github/workflows/build_loop.yml
+++ b/.github/workflows/build_loop.yml
@@ -1,15 +1,14 @@
 name: 4. Build Loop
 run-name: Build Loop (${{ github.ref_name }})
-
 on:
   workflow_dispatch:
 
-  # Uncomment de regel hieronder als je ook builds wilt op elke push
+  # Automated builds on schedule (commented out push trigger)
   #push:
 
   schedule:
-    - cron: "33 9 * * 3" # Checks for updates at 09:33 UTC every Wednesday
-    - cron: "33 7 1 * *" # Builds the app on the 1st of every month at 07:33 UTC
+    - cron: "33 9 * * 3" # Every Wednesday 09:33 UTC
+    - cron: "33 7 1 * *" # 1st of each month 07:33 UTC
 
 env:
   UPSTREAM_REPO: LoopKit/LoopWorkspace
@@ -19,7 +18,7 @@ env:
   ALIVE_BRANCH_DEV: alive-dev
 
 jobs:
-  check_certs:
+  check_certs: 
     name: Check certificates
     uses: ./.github/workflows/create_certs.yml
     secrets: inherit
@@ -32,7 +31,6 @@ jobs:
       contents: write
     outputs:
       WORKFLOW_PERMISSION: ${{ steps.workflow-permission.outputs.has_permission }}
-
     steps:
       - name: Check for workflow permissions
         id: workflow-permission
@@ -41,10 +39,12 @@ jobs:
         run: |
           PERMISSIONS=$(curl -sS -f -I -H "Authorization: token ${{ env.TOKEN_TO_CHECK }}" https://api.github.com | grep ^x-oauth-scopes: | cut -d' ' -f2-);
           if [[ $PERMISSIONS =~ "workflow" || $PERMISSIONS == "" ]]; then
+            echo "GH_PAT holds workflow permissions or is fine-grained PAT."
             echo "has_permission=true" >> $GITHUB_OUTPUT
           else 
+            echo "GH_PAT lacks workflow permissions."
+            echo "Automated build features will be skipped!"
             echo "has_permission=false" >> $GITHUB_OUTPUT
-          fi
 
       - name: Check for alive branches
         if: steps.workflow-permission.outputs.has_permission == 'true'
@@ -52,10 +52,11 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GH_PAT }}
         run: |
           if [[ $(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/LoopWorkspace/branches | jq --raw-output '[.[] | select(.name == "alive-main" or .name == "alive-dev")] | length > 0') == "true" ]]; then
+            echo "Branches 'alive-main' or 'alive-dev' exist."
             echo "ALIVE_BRANCH_EXISTS=true" >> $GITHUB_ENV
           else
+            echo "Branches 'alive-main' and 'alive-dev' do not exist."
             echo "ALIVE_BRANCH_EXISTS=false" >> $GITHUB_ENV
-          fi
 
       - name: Create alive branches
         if: env.ALIVE_BRANCH_EXISTS == 'false'
@@ -74,9 +75,9 @@ jobs:
     outputs:
       NEW_COMMITS: ${{ steps.sync.outputs.has_new_commits }}
       ABORT_SYNC: ${{ steps.check_branch.outputs.ABORT_SYNC }}
-
     steps:
       - name: Check if running on main or dev branch
+        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && (vars.SCHEDULED_BUILD != 'false' || vars.SCHEDULED_SYNC != 'false')
         id: check_branch
         run: |
           if [ "${GITHUB_REF##*/}" = "main" ]; then
@@ -87,17 +88,16 @@ jobs:
             echo "ABORT_SYNC=false" >> $GITHUB_OUTPUT
           else
             echo "ABORT_SYNC=true" >> $GITHUB_OUTPUT
-          fi
 
       - name: Checkout target repo
-        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true'
+        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && (vars.SCHEDULED_BUILD != 'false' || vars.SCHEDULED_SYNC != 'false')
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.GH_PAT }}
           ref: ${{ steps.check_branch.outputs.ALIVE_BRANCH }}
 
       - name: Sync upstream changes
-        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && github.repository_owner != 'LoopKit' && steps.check_branch.outputs.ABORT_SYNC == 'false'
+        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && vars.SCHEDULED_SYNC != 'false' && github.repository_owner != 'LoopKit' && steps.check_branch.outputs.ABORT_SYNC == 'false'
         id: sync
         uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
         with:
@@ -108,8 +108,10 @@ jobs:
           upstream_sync_repo: ${{ env.UPSTREAM_REPO }}
 
       - name: Show value of 'has_new_commits'
-        if: steps.check_branch.outputs.ABORT_SYNC == 'false'
-        run: echo "NEW_COMMITS=${{ steps.sync.outputs.has_new_commits }}" >> $GITHUB_OUTPUT
+        if: needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && vars.SCHEDULED_SYNC != 'false' && steps.check_branch.outputs.ABORT_SYNC == 'false'
+        run: |
+          echo ${{ steps.sync.outputs.has_new_commits }}
+          echo "NEW_COMMITS=${{ steps.sync.outputs.has_new_commits }}" >> $GITHUB_OUTPUT
 
   build:
     name: Build
@@ -117,11 +119,7 @@ jobs:
     runs-on: macos-15
     permissions:
       contents: write
-    if: github.event_name == 'workflow_dispatch' ||
-        (needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' &&
-        ((vars.SCHEDULED_BUILD != 'false' && github.event.schedule == '33 7 1 * *') ||
-        (vars.SCHEDULED_SYNC != 'false' && needs.check_latest_from_upstream.outputs.NEW_COMMITS == 'true')))
-
+    if: github.event_name == 'workflow_dispatch' || (needs.check_alive_and_permissions.outputs.WORKFLOW_PERMISSION == 'true' && ((vars.SCHEDULED_BUILD != 'false' && github.event.schedule == '33 7 1 * *') || (vars.SCHEDULED_SYNC != 'false' && needs.check_latest_from_upstream.outputs.NEW_COMMITS == 'true')))
     steps:
       - name: Select Xcode version
         run: sudo xcode-select --switch /Applications/Xcode_16.4.app/Contents/Developer
@@ -135,7 +133,7 @@ jobs:
 
       - name: Customize Loop
         run: |
-          if ls ./patches/* &> /dev/null; then
+          if $(ls ./patches/* &> /dev/null); then
             git apply ./patches/* --allow-empty -v --whitespace=fix
           fi
 
@@ -144,6 +142,9 @@ jobs:
           TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
           if [ -f "$TABLE_PRINTER_PATH" ]; then
             sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
+          else
+            echo "table_printer.rb not found"
+            exit 1
           fi
 
       - name: Install Project Dependencies
@@ -172,7 +173,7 @@ jobs:
           FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
           MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
 
-      - name: Upload build log, IPA and Symbol artifacts
+      - name: Upload build artifacts
         if: always()
         uses: actions/upload-artifact@v4
         with:
